# Generated by Django 5.1 on 2024-09-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_file_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
